/**
 * Next.js 15 Generator Module
 *
 * Generates a complete Next.js 15 App Router project with:
 * - App Router structure (app/ directory)
 * - Drizzle ORM database integration
 * - Auth.js or Lucia authentication
 * - Tailwind CSS v4 styling
 * - TypeScript configuration
 * - API routes (public and authenticated)
 * - Middleware for auth protection
 */

import path from 'path';
import {
  BaseGenerator,
  type ProjectConfig,
  type GenerationResult,
  generateNextJsPackageJson,
  generateNextJsTsConfig,
  getTemplateDir,
  writeFile,
} from './base.js';

// =============================================================================
// NEXT.JS SPECIFIC CONTENT GENERATORS
// =============================================================================

/**
 * Generates next.config.ts content
 */
function generateNextConfig(config: ProjectConfig): string {
  const standaloneOutput = config.deployment === 'docker' ? '\n  output: "standalone",' : '';

  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,${standaloneOutput}
  experimental: {
    serverActions: {
      bodySizeLimit: "2mb",
    },
  },
};

export default nextConfig;
`;
}

/**
 * Generates app/layout.tsx content
 */
function generateRootLayout(config: ProjectConfig): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${config.name}",
  description: "Generated by stackgen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background text-foreground antialiased">
        {children}
      </body>
    </html>
  );
}
`;
}

/**
 * Generates app/page.tsx content
 */
function generateHomePage(config: ProjectConfig): string {
  return `import Link from "next/link";

export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="text-center space-y-8">
        <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
          Welcome to ${config.name}
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl">
          Your Next.js 15 project is ready! Built with App Router, Drizzle ORM,
          ${config.auth === 'authjs' ? 'Auth.js' : 'Lucia'}, and Tailwind CSS.
        </p>
        <div className="flex gap-4 justify-center">
          <Link
            href="/dashboard"
            className="rounded-lg bg-blue-600 px-6 py-3 text-white font-medium hover:bg-blue-700 transition-colors"
          >
            Go to Dashboard
          </Link>
          <Link
            href="/api/health"
            className="rounded-lg border border-gray-300 dark:border-gray-700 px-6 py-3 font-medium hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            Check API Health
          </Link>
        </div>
      </div>
    </main>
  );
}
`;
}

/**
 * Generates app/globals.css content (Tailwind CSS v4)
 */
function generateGlobalsCss(): string {
  return `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    "Helvetica Neue", Arial, sans-serif;
}
`;
}

/**
 * Generates app/loading.tsx content
 */
function generateLoadingPage(): string {
  return `export default function Loading() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent" />
    </div>
  );
}
`;
}

/**
 * Generates app/error.tsx content
 */
function generateErrorPage(): string {
  return `"use client";

import { useEffect } from "react";

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error);
  }, [error]);

  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <h2 className="text-2xl font-bold mb-4">Something went wrong!</h2>
      <button
        onClick={() => reset()}
        className="rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 transition-colors"
      >
        Try again
      </button>
    </div>
  );
}
`;
}

/**
 * Generates app/not-found.tsx content
 */
function generateNotFoundPage(): string {
  return `import Link from "next/link";

export default function NotFound() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <h2 className="text-2xl font-bold mb-2">404 - Page Not Found</h2>
      <p className="text-gray-600 dark:text-gray-400 mb-4">
        The page you are looking for does not exist.
      </p>
      <Link
        href="/"
        className="rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 transition-colors"
      >
        Return Home
      </Link>
    </div>
  );
}
`;
}

/**
 * Generates app/dashboard/page.tsx content
 */
function generateDashboardPage(config: ProjectConfig): string {
  if (config.auth === 'authjs') {
    return `import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { SignOutButton } from "@/components/auth/sign-out-button";

export default async function DashboardPage() {
  const session = await auth();

  if (!session?.user) {
    redirect("/auth/signin");
  }

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">Dashboard</h1>
          <SignOutButton />
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-xl font-semibold mb-4">Welcome, {session.user.name || session.user.email}!</h2>
          <p className="text-gray-600 dark:text-gray-400">
            You are successfully authenticated. This is a protected page.
          </p>
          <div className="mt-4 p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
            <h3 className="font-medium mb-2">Session Info:</h3>
            <pre className="text-sm overflow-auto">
              {JSON.stringify(session, null, 2)}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
`;
  }

  // Lucia version
  return `import { validateRequest } from "@/lib/auth";
import { redirect } from "next/navigation";
import { SignOutButton } from "@/components/auth/sign-out-button";

export default async function DashboardPage() {
  const { user, session } = await validateRequest();

  if (!user) {
    redirect("/auth/signin");
  }

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">Dashboard</h1>
          <SignOutButton />
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-xl font-semibold mb-4">Welcome, {user.name || user.email}!</h2>
          <p className="text-gray-600 dark:text-gray-400">
            You are successfully authenticated. This is a protected page.
          </p>
          <div className="mt-4 p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
            <h3 className="font-medium mb-2">User Info:</h3>
            <pre className="text-sm overflow-auto">
              {JSON.stringify({ user, sessionId: session.id }, null, 2)}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
`;
}

/**
 * Generates app/auth/signin/page.tsx content
 */
function generateSignInPage(config: ProjectConfig): string {
  if (config.auth === 'authjs') {
    return `"use client";

import { signIn } from "next-auth/react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function SignInPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const result = await signIn("credentials", {
        email,
        password,
        redirect: false,
      });

      if (result?.error) {
        setError("Invalid email or password");
      } else {
        router.push("/dashboard");
        router.refresh();
      }
    } catch {
      setError("An error occurred. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Sign In</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            Welcome back! Please sign in to continue.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {error && (
            <div className="bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 p-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div>
            <label htmlFor="email" className="block text-sm font-medium mb-2">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium mb-2">
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="Enter your password"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {loading ? "Signing in..." : "Sign In"}
          </button>
        </form>

        <p className="text-center text-sm text-gray-600 dark:text-gray-400">
          Don&apos;t have an account?{" "}
          <Link href="/auth/signup" className="text-blue-600 hover:underline">
            Sign Up
          </Link>
        </p>
      </div>
    </div>
  );
}
`;
  }

  // Lucia version
  return `"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function SignInPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const response = await fetch("/api/auth/signin", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || "Invalid email or password");
      } else {
        router.push("/dashboard");
        router.refresh();
      }
    } catch {
      setError("An error occurred. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Sign In</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            Welcome back! Please sign in to continue.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {error && (
            <div className="bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 p-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div>
            <label htmlFor="email" className="block text-sm font-medium mb-2">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium mb-2">
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="Enter your password"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {loading ? "Signing in..." : "Sign In"}
          </button>
        </form>

        <p className="text-center text-sm text-gray-600 dark:text-gray-400">
          Don&apos;t have an account?{" "}
          <Link href="/auth/signup" className="text-blue-600 hover:underline">
            Sign Up
          </Link>
        </p>
      </div>
    </div>
  );
}
`;
}

/**
 * Generates app/auth/signup/page.tsx content
 */
function generateSignUpPage(config: ProjectConfig): string {
  const apiEndpoint = config.auth === 'authjs' ? '/api/auth/register' : '/api/auth/signup';

  return `"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function SignUpPage() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (password !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    if (password.length < 8) {
      setError("Password must be at least 8 characters");
      return;
    }

    setLoading(true);

    try {
      const response = await fetch("${apiEndpoint}", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, email, password }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || "Failed to create account");
      } else {
        router.push("/auth/signin?registered=true");
      }
    } catch {
      setError("An error occurred. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-md space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Create Account</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            Sign up to get started.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {error && (
            <div className="bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 p-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div>
            <label htmlFor="name" className="block text-sm font-medium mb-2">
              Name
            </label>
            <input
              id="name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="Your name"
            />
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium mb-2">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium mb-2">
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              minLength={8}
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="At least 8 characters"
            />
          </div>

          <div>
            <label htmlFor="confirmPassword" className="block text-sm font-medium mb-2">
              Confirm Password
            </label>
            <input
              id="confirmPassword"
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              required
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="Confirm your password"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {loading ? "Creating account..." : "Sign Up"}
          </button>
        </form>

        <p className="text-center text-sm text-gray-600 dark:text-gray-400">
          Already have an account?{" "}
          <Link href="/auth/signin" className="text-blue-600 hover:underline">
            Sign In
          </Link>
        </p>
      </div>
    </div>
  );
}
`;
}

/**
 * Generates app/api/health/route.ts content
 */
function generateHealthRoute(): string {
  return `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    status: "ok",
    timestamp: new Date().toISOString(),
  });
}
`;
}

/**
 * Generates app/api/auth/register/route.ts content (for Auth.js)
 */
function generateRegisterRoute(_config: ProjectConfig): string {
  return `import { NextRequest, NextResponse } from "next/server";
import { hash } from "bcryptjs";
import { db } from "@/db";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod";

const registerSchema = z.object({
  name: z.string().min(1, "Name is required"),
  email: z.string().email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters"),
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validation = registerSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0]?.message || "Invalid input" },
        { status: 400 }
      );
    }

    const { name, email, password } = validation.data;

    // Check if user already exists
    const existingUser = await db.query.users.findFirst({
      where: eq(users.email, email.toLowerCase()),
    });

    if (existingUser) {
      return NextResponse.json(
        { error: "Email already registered" },
        { status: 409 }
      );
    }

    // Hash password
    const passwordHash = await hash(password, 12);

    // Create user
    const [newUser] = await db
      .insert(users)
      .values({
        name,
        email: email.toLowerCase(),
        passwordHash,
      })
      .returning({ id: users.id, email: users.email });

    return NextResponse.json(
      { message: "Account created successfully", user: { id: newUser?.id, email: newUser?.email } },
      { status: 201 }
    );
  } catch (error) {
    console.error("Registration error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
`;
}

/**
 * Generates middleware.ts content
 */
function generateMiddleware(config: ProjectConfig): string {
  if (config.auth === 'authjs') {
    return `export { auth as middleware } from "@/lib/auth";

export const config = {
  // Match all paths except static files, api routes that don't need auth, and public files
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api/health (public health check endpoint)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - public files (public folder)
     */
    "/((?!api/health|_next/static|_next/image|favicon.ico|.*\\..*|api/auth).*)",
  ],
};
`;
  }

  // Lucia middleware
  return `import { NextRequest, NextResponse } from "next/server";

// Protected routes that require authentication
const protectedRoutes = ["/dashboard", "/settings", "/profile"];

// Auth routes that should redirect logged-in users
const authRoutes = ["/auth/signin", "/auth/signup"];

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Check for session cookie
  const sessionCookie = request.cookies.get("auth_session");
  const isAuthenticated = !!sessionCookie?.value;

  // Redirect logged-in users away from auth pages
  if (isAuthenticated && authRoutes.some((route) => pathname.startsWith(route))) {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }

  // Redirect unauthenticated users from protected routes
  if (!isAuthenticated && protectedRoutes.some((route) => pathname.startsWith(route))) {
    const signInUrl = new URL("/auth/signin", request.url);
    signInUrl.searchParams.set("callbackUrl", pathname);
    return NextResponse.redirect(signInUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - public files
     */
    "/((?!api|_next/static|_next/image|favicon.ico|.*\\..*).*)",
  ],
};
`;
}

/**
 * Generates lib/auth.ts content for Auth.js
 */
function generateAuthJsConfig(_config: ProjectConfig): string {
  return `import NextAuth from "next-auth";
import Credentials from "next-auth/providers/credentials";
import { DrizzleAdapter } from "@auth/drizzle-adapter";
import { compare } from "bcryptjs";
import { db } from "@/db";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod";

const credentialsSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
});

export const { handlers, signIn, signOut, auth } = NextAuth({
  adapter: DrizzleAdapter(db),
  session: { strategy: "jwt" },
  pages: {
    signIn: "/auth/signin",
    error: "/auth/error",
  },
  providers: [
    Credentials({
      name: "credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        const parsed = credentialsSchema.safeParse(credentials);
        if (!parsed.success) return null;

        const { email, password } = parsed.data;

        const user = await db.query.users.findFirst({
          where: eq(users.email, email.toLowerCase()),
        });

        if (!user?.passwordHash) return null;

        const passwordMatch = await compare(password, user.passwordHash);
        if (!passwordMatch) return null;

        return {
          id: user.id,
          email: user.email,
          name: user.name,
          image: user.image,
        };
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id;
      }
      return token;
    },
    async session({ session, token }) {
      if (session.user && token.id) {
        session.user.id = token.id as string;
      }
      return session;
    },
  },
});
`;
}

/**
 * Generates lib/auth.ts content for Lucia
 */
function generateLuciaConfig(config: ProjectConfig): string {
  const adapterImport = config.database === 'postgresql'
    ? `import { DrizzlePostgreSQLAdapter } from "@lucia-auth/adapter-drizzle";`
    : `import { DrizzleSQLiteAdapter } from "@lucia-auth/adapter-drizzle";`;

  const adapterInit = config.database === 'postgresql'
    ? `const adapter = new DrizzlePostgreSQLAdapter(db, sessions, users);`
    : `const adapter = new DrizzleSQLiteAdapter(db, sessions, users);`;

  return `import { Lucia } from "lucia";
${adapterImport}
import { db } from "@/db";
import { sessions, users } from "@/db/schema";
import { cookies } from "next/headers";
import { cache } from "react";

${adapterInit}

export const lucia = new Lucia(adapter, {
  sessionCookie: {
    expires: false,
    attributes: {
      secure: process.env.NODE_ENV === "production",
    },
  },
  getUserAttributes: (attributes) => {
    return {
      email: attributes.email,
      name: attributes.name,
      image: attributes.image,
    };
  },
});

declare module "lucia" {
  interface Register {
    Lucia: typeof lucia;
    DatabaseUserAttributes: {
      email: string;
      name: string | null;
      image: string | null;
    };
  }
}

export const validateRequest = cache(async () => {
  const cookieStore = await cookies();
  const sessionId = cookieStore.get(lucia.sessionCookieName)?.value ?? null;

  if (!sessionId) {
    return { user: null, session: null };
  }

  const result = await lucia.validateSession(sessionId);

  try {
    if (result.session && result.session.fresh) {
      const sessionCookie = lucia.createSessionCookie(result.session.id);
      cookieStore.set(
        sessionCookie.name,
        sessionCookie.value,
        sessionCookie.attributes
      );
    }
    if (!result.session) {
      const sessionCookie = lucia.createBlankSessionCookie();
      cookieStore.set(
        sessionCookie.name,
        sessionCookie.value,
        sessionCookie.attributes
      );
    }
  } catch {
    // Next.js throws when you attempt to set cookie when rendering page
  }

  return result;
});
`;
}

/**
 * Generates Lucia auth API routes
 */
function generateLuciaSignInRoute(_config: ProjectConfig): string {
  return `import { NextRequest, NextResponse } from "next/server";
import { compare } from "bcryptjs";
import { cookies } from "next/headers";
import { lucia } from "@/lib/auth";
import { db } from "@/db";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod";

const signInSchema = z.object({
  email: z.string().email("Invalid email address"),
  password: z.string().min(1, "Password is required"),
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validation = signInSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0]?.message || "Invalid input" },
        { status: 400 }
      );
    }

    const { email, password } = validation.data;

    const user = await db.query.users.findFirst({
      where: eq(users.email, email.toLowerCase()),
    });

    if (!user?.passwordHash) {
      return NextResponse.json(
        { error: "Invalid email or password" },
        { status: 401 }
      );
    }

    const validPassword = await compare(password, user.passwordHash);
    if (!validPassword) {
      return NextResponse.json(
        { error: "Invalid email or password" },
        { status: 401 }
      );
    }

    const session = await lucia.createSession(user.id, {});
    const sessionCookie = lucia.createSessionCookie(session.id);

    const cookieStore = await cookies();
    cookieStore.set(
      sessionCookie.name,
      sessionCookie.value,
      sessionCookie.attributes
    );

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Sign in error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
`;
}

function generateLuciaSignUpRoute(_config: ProjectConfig): string {
  return `import { NextRequest, NextResponse } from "next/server";
import { hash } from "bcryptjs";
import { cookies } from "next/headers";
import { lucia } from "@/lib/auth";
import { db } from "@/db";
import { users } from "@/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { generateIdFromEntropySize } from "lucia";

const signUpSchema = z.object({
  name: z.string().min(1, "Name is required"),
  email: z.string().email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters"),
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const validation = signUpSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.errors[0]?.message || "Invalid input" },
        { status: 400 }
      );
    }

    const { name, email, password } = validation.data;

    // Check if user already exists
    const existingUser = await db.query.users.findFirst({
      where: eq(users.email, email.toLowerCase()),
    });

    if (existingUser) {
      return NextResponse.json(
        { error: "Email already registered" },
        { status: 409 }
      );
    }

    // Hash password
    const passwordHash = await hash(password, 12);

    // Create user
    const userId = generateIdFromEntropySize(10);
    await db.insert(users).values({
      id: userId,
      name,
      email: email.toLowerCase(),
      passwordHash,
    });

    // Create session
    const session = await lucia.createSession(userId, {});
    const sessionCookie = lucia.createSessionCookie(session.id);

    const cookieStore = await cookies();
    cookieStore.set(
      sessionCookie.name,
      sessionCookie.value,
      sessionCookie.attributes
    );

    return NextResponse.json(
      { success: true },
      { status: 201 }
    );
  } catch (error) {
    console.error("Sign up error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
`;
}

function generateLuciaSignOutRoute(): string {
  return `import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { lucia, validateRequest } from "@/lib/auth";

export async function POST() {
  try {
    const { session } = await validateRequest();

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await lucia.invalidateSession(session.id);

    const sessionCookie = lucia.createBlankSessionCookie();
    const cookieStore = await cookies();
    cookieStore.set(
      sessionCookie.name,
      sessionCookie.value,
      sessionCookie.attributes
    );

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Sign out error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
`;
}

/**
 * Generates components/auth/sign-out-button.tsx
 */
function generateSignOutButton(config: ProjectConfig): string {
  if (config.auth === 'authjs') {
    return `"use client";

import { signOut } from "next-auth/react";

export function SignOutButton() {
  return (
    <button
      onClick={() => signOut({ callbackUrl: "/" })}
      className="rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
    >
      Sign Out
    </button>
  );
}
`;
  }

  // Lucia version
  return `"use client";

import { useRouter } from "next/navigation";

export function SignOutButton() {
  const router = useRouter();

  const handleSignOut = async () => {
    try {
      await fetch("/api/auth/signout", { method: "POST" });
      router.push("/");
      router.refresh();
    } catch (error) {
      console.error("Sign out failed:", error);
    }
  };

  return (
    <button
      onClick={handleSignOut}
      className="rounded-lg border border-gray-300 dark:border-gray-700 px-4 py-2 text-sm font-medium hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
    >
      Sign Out
    </button>
  );
}
`;
}

/**
 * Generates lib/utils.ts content
 */
function generateUtils(): string {
  return `import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Combines class names with tailwind-merge
 * Useful for conditional classes and avoiding conflicts
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;
}

/**
 * Generates postcss.config.mjs content (Tailwind CSS v4)
 */
function generatePostCssConfig(): string {
  return `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`;
}

// =============================================================================
// NEXT.JS GENERATOR CLASS
// =============================================================================

export class NextJsGenerator extends BaseGenerator {
  constructor(config: ProjectConfig, destPath: string) {
    super(config, destPath);
  }

  async generate(): Promise<GenerationResult> {
    try {
      // Create project structure
      await this.createDirectoryStructure();

      // Generate configuration files
      await this.generatePackageJson();
      await this.generateTsConfig();
      await this.generateNextConfig();
      await this.generatePostCssConfig();

      // Generate app structure
      await this.generateAppStructure();

      // Generate API routes
      await this.generateApiRoutes();

      // Generate auth configuration
      await this.generateAuthConfig();

      // Generate components
      await this.generateComponents();

      // Generate lib utilities
      await this.generateLibFiles();

      // Generate middleware
      await this.generateMiddlewareFile();

      // Generate Drizzle files
      await this.setupDrizzle();

      // Generate shared files (gitignore, prettier, docker, etc.)
      await this.setupSharedFiles();

      // Copy any existing templates
      const templateDir = getTemplateDir('nextjs');
      await this.copyTemplateFiles(templateDir);

      return this.createResult(true, 'Next.js project generated successfully');
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.errors.push(errorMessage);
      return this.createResult(false, `Failed to generate Next.js project: ${errorMessage}`);
    }
  }

  private async createDirectoryStructure(): Promise<void> {
    const directories = [
      'app',
      'app/api',
      'app/api/health',
      'app/api/auth',
      'app/auth/signin',
      'app/auth/signup',
      'app/dashboard',
      'components',
      'components/auth',
      'components/ui',
      'lib',
      'src/db',
      'src/db/schema',
      'drizzle/migrations',
      'public',
    ];

    if (this.config.auth === 'lucia') {
      directories.push('app/api/auth/signin', 'app/api/auth/signup', 'app/api/auth/signout');
    } else {
      directories.push('app/api/auth/register');
    }

    const fsExtra = await import('fs-extra');
    for (const dir of directories) {
      const dirPath = path.join(this.destPath, dir);
      await fsExtra.default.ensureDir(dirPath);
    }
  }

  protected async generatePackageJson(): Promise<void> {
    const packageJson = generateNextJsPackageJson(this.config);
    await this.writeProjectJsonFile('package.json', packageJson);
  }

  protected async generateTsConfig(): Promise<void> {
    const tsConfig = generateNextJsTsConfig();
    await this.writeProjectJsonFile('tsconfig.json', tsConfig);
  }

  private async generateNextConfig(): Promise<void> {
    await this.writeProjectFile('next.config.ts', generateNextConfig(this.config));
  }

  private async generatePostCssConfig(): Promise<void> {
    await this.writeProjectFile('postcss.config.mjs', generatePostCssConfig());
  }

  private async generateAppStructure(): Promise<void> {
    // Layout
    await this.writeProjectFile('app/layout.tsx', generateRootLayout(this.config));

    // Home page
    await this.writeProjectFile('app/page.tsx', generateHomePage(this.config));

    // Global styles
    await this.writeProjectFile('app/globals.css', generateGlobalsCss());

    // Loading state
    await this.writeProjectFile('app/loading.tsx', generateLoadingPage());

    // Error boundary
    await this.writeProjectFile('app/error.tsx', generateErrorPage());

    // 404 page
    await this.writeProjectFile('app/not-found.tsx', generateNotFoundPage());

    // Dashboard page
    await this.writeProjectFile('app/dashboard/page.tsx', generateDashboardPage(this.config));

    // Auth pages
    await this.writeProjectFile('app/auth/signin/page.tsx', generateSignInPage(this.config));
    await this.writeProjectFile('app/auth/signup/page.tsx', generateSignUpPage(this.config));
  }

  private async generateApiRoutes(): Promise<void> {
    // Health check route
    await this.writeProjectFile('app/api/health/route.ts', generateHealthRoute());

    if (this.config.auth === 'authjs') {
      // Registration route for Auth.js
      await this.writeProjectFile(
        'app/api/auth/register/route.ts',
        generateRegisterRoute(this.config)
      );

      // Auth.js route handler
      await this.writeProjectFile(
        'app/api/auth/[...nextauth]/route.ts',
        `import { handlers } from "@/lib/auth";
export const { GET, POST } = handlers;
`
      );
    } else {
      // Lucia auth routes
      await this.writeProjectFile(
        'app/api/auth/signin/route.ts',
        generateLuciaSignInRoute(this.config)
      );
      await this.writeProjectFile(
        'app/api/auth/signup/route.ts',
        generateLuciaSignUpRoute(this.config)
      );
      await this.writeProjectFile(
        'app/api/auth/signout/route.ts',
        generateLuciaSignOutRoute()
      );
    }
  }

  private async generateAuthConfig(): Promise<void> {
    if (this.config.auth === 'authjs') {
      await this.writeProjectFile('lib/auth.ts', generateAuthJsConfig(this.config));
    } else {
      await this.writeProjectFile('lib/auth.ts', generateLuciaConfig(this.config));
    }
  }

  private async generateComponents(): Promise<void> {
    // Sign out button
    await this.writeProjectFile(
      'components/auth/sign-out-button.tsx',
      generateSignOutButton(this.config)
    );

    // Example button component
    await this.writeProjectFile(
      'components/ui/button.tsx',
      `import { cn } from "@/lib/utils";
import { forwardRef, type ButtonHTMLAttributes } from "react";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "outline" | "ghost";
  size?: "sm" | "md" | "lg";
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "default", size = "md", ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          "inline-flex items-center justify-center rounded-lg font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed",
          {
            "bg-blue-600 text-white hover:bg-blue-700": variant === "default",
            "border border-gray-300 dark:border-gray-700 hover:bg-gray-100 dark:hover:bg-gray-800":
              variant === "outline",
            "hover:bg-gray-100 dark:hover:bg-gray-800": variant === "ghost",
          },
          {
            "px-3 py-1.5 text-sm": size === "sm",
            "px-4 py-2 text-base": size === "md",
            "px-6 py-3 text-lg": size === "lg",
          },
          className
        )}
        {...props}
      />
    );
  }
);

Button.displayName = "Button";
`
    );
  }

  private async generateLibFiles(): Promise<void> {
    // Utils
    await this.writeProjectFile('lib/utils.ts', generateUtils());
  }

  private async generateMiddlewareFile(): Promise<void> {
    await this.writeProjectFile('middleware.ts', generateMiddleware(this.config));
  }

  protected override async setupDrizzle(): Promise<void> {
    // Override to use correct paths for Next.js
    // Create custom paths for Next.js (db in src/db)
    await writeFile(
      path.join(this.destPath, 'drizzle.config.ts'),
      this.generateNextJsDrizzleConfig()
    );
    this.createdFiles.push(path.join(this.destPath, 'drizzle.config.ts'));

    // Create database client
    await writeFile(
      path.join(this.destPath, 'src', 'db', 'index.ts'),
      this.generateNextJsDbClient()
    );
    this.createdFiles.push(path.join(this.destPath, 'src', 'db', 'index.ts'));

    // Create schema files using base generator
    const { generateUsersSchema, generateSessionsSchema, generateAccountsSchema, generateVerificationTokensSchema, generateSchemaIndex } = await import('./base.js');

    const schemaDir = path.join(this.destPath, 'src', 'db', 'schema');

    await writeFile(path.join(schemaDir, 'users.ts'), generateUsersSchema(this.config));
    await writeFile(path.join(schemaDir, 'sessions.ts'), generateSessionsSchema(this.config));

    if (this.config.auth === 'authjs') {
      await writeFile(path.join(schemaDir, 'accounts.ts'), generateAccountsSchema(this.config));
      await writeFile(path.join(schemaDir, 'verificationTokens.ts'), generateVerificationTokensSchema(this.config));
    }

    await writeFile(path.join(schemaDir, 'index.ts'), generateSchemaIndex(this.config));

    this.createdFiles.push(
      path.join(schemaDir, 'users.ts'),
      path.join(schemaDir, 'sessions.ts'),
      path.join(schemaDir, 'index.ts')
    );

    if (this.config.auth === 'authjs') {
      this.createdFiles.push(
        path.join(schemaDir, 'accounts.ts'),
        path.join(schemaDir, 'verificationTokens.ts')
      );
    }

    // Create migrations directory
    const migrationsDir = path.join(this.destPath, 'drizzle', 'migrations');
    const fsExtra = await import('fs-extra');
    await fsExtra.default.ensureDir(migrationsDir);
    await writeFile(path.join(migrationsDir, '.gitkeep'), '');
  }

  private generateNextJsDrizzleConfig(): string {
    if (this.config.database === 'postgresql') {
      return `import type { Config } from 'drizzle-kit';
import * as dotenv from 'dotenv';

dotenv.config();

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL environment variable is required');
}

export default {
  schema: './src/db/schema/index.ts',
  out: './drizzle/migrations',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  verbose: true,
  strict: true,
} satisfies Config;
`;
    }

    return `import type { Config } from 'drizzle-kit';
import * as dotenv from 'dotenv';

dotenv.config();

const dbPath = process.env.DATABASE_PATH || './data/${this.config.name}.db';

export default {
  schema: './src/db/schema/index.ts',
  out: './drizzle/migrations',
  dialect: 'sqlite',
  dbCredentials: {
    url: dbPath,
  },
  verbose: true,
  strict: true,
} satisfies Config;
`;
  }

  private generateNextJsDbClient(): string {
    if (this.config.database === 'postgresql') {
      return `import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema';

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL environment variable is required');
}

const connectionString = process.env.DATABASE_URL;

const queryClient = postgres(connectionString, {
  max: 10,
  idle_timeout: 20,
  connect_timeout: 10,
});

export const db = drizzle(queryClient, { schema });

export type Database = typeof db;
`;
    }

    return `import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
import * as schema from './schema';
import path from 'path';
import fs from 'fs';

const dbPath = process.env.DATABASE_PATH || './data/${this.config.name}.db';
const dbDir = path.dirname(dbPath);

if (!fs.existsSync(dbDir)) {
  fs.mkdirSync(dbDir, { recursive: true });
}

const sqlite = new Database(dbPath);
sqlite.pragma('journal_mode = WAL');

export const db = drizzle(sqlite, { schema });

export type Database = typeof db;
`;
  }
}

// =============================================================================
// STANDALONE GENERATE FUNCTION
// =============================================================================

/**
 * Standalone function to generate a Next.js project
 * Can be used without instantiating the class
 */
export async function generate(
  config: ProjectConfig,
  destPath: string
): Promise<GenerationResult> {
  const generator = new NextJsGenerator(config, destPath);
  return generator.generate();
}

export default NextJsGenerator;
